import http from 'node:http';
import crypto from 'node:crypto';
import { promisify } from 'node:util';
import { db, migrate } from './lib/db.js';

const scrypt = promisify(crypto.scrypt);
const PORT = Number(process.env.PORT || 3000);
const COOKIE = 'darsban_session';
const SESSION_MS = 30 * 24 * 60 * 60 * 1000;
const OTP_SECRET = process.env.OTP_SECRET || 'darsban-local-development-secret-change-in-production';
const ADMIN_USER = 'owner';
const ADMIN_PASSWORD = 'Db!9374Secure';

migrate(`
CREATE TABLE IF NOT EXISTS academic_years (id INTEGER PRIMARY KEY, title TEXT NOT NULL UNIQUE, active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS curriculum_versions (id INTEGER PRIMARY KEY AUTOINCREMENT, academic_year_id INTEGER NOT NULL REFERENCES academic_years(id), grade INTEGER NOT NULL CHECK(grade IN (10,11,12)), field TEXT NOT NULL CHECK(field IN ('math','science','humanities')), status TEXT NOT NULL CHECK(status IN ('draft','review','published','archived')), title TEXT NOT NULL, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, UNIQUE(academic_year_id,grade,field,status) ON CONFLICT ABORT);
CREATE TABLE IF NOT EXISTS subjects (id INTEGER PRIMARY KEY AUTOINCREMENT, curriculum_version_id INTEGER NOT NULL REFERENCES curriculum_versions(id) ON DELETE CASCADE, name TEXT NOT NULL, sort_order INTEGER NOT NULL DEFAULT 0, UNIQUE(curriculum_version_id,name));
CREATE TABLE IF NOT EXISTS books (id INTEGER PRIMARY KEY AUTOINCREMENT, subject_id INTEGER NOT NULL REFERENCES subjects(id) ON DELETE CASCADE, name TEXT NOT NULL, sort_order INTEGER NOT NULL DEFAULT 0, UNIQUE(subject_id,name));
CREATE TABLE IF NOT EXISTS chapters (id INTEGER PRIMARY KEY AUTOINCREMENT, book_id INTEGER NOT NULL REFERENCES books(id) ON DELETE CASCADE, name TEXT NOT NULL, sort_order INTEGER NOT NULL DEFAULT 0, UNIQUE(book_id,name));
CREATE TABLE IF NOT EXISTS lessons (id INTEGER PRIMARY KEY AUTOINCREMENT, chapter_id INTEGER NOT NULL REFERENCES chapters(id) ON DELETE CASCADE, name TEXT NOT NULL, sort_order INTEGER NOT NULL DEFAULT 0, UNIQUE(chapter_id,name));
CREATE TABLE IF NOT EXISTS topics (id INTEGER PRIMARY KEY AUTOINCREMENT, lesson_id INTEGER NOT NULL REFERENCES lessons(id) ON DELETE CASCADE, name TEXT NOT NULL, sort_order INTEGER NOT NULL DEFAULT 0, UNIQUE(lesson_id,name));
CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, first_name TEXT NOT NULL, last_name TEXT NOT NULL, phone TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL, verified INTEGER NOT NULL DEFAULT 0, role TEXT NOT NULL DEFAULT 'student', created_at INTEGER NOT NULL, deleted_at INTEGER);
CREATE TABLE IF NOT EXISTS user_profiles (user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE, grade INTEGER NOT NULL, field TEXT NOT NULL, academic_year_id INTEGER NOT NULL REFERENCES academic_years(id), timezone TEXT NOT NULL, daily_goal INTEGER NOT NULL DEFAULT 7200, curriculum_version_id INTEGER REFERENCES curriculum_versions(id));
CREATE TABLE IF NOT EXISTS user_settings (user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE, theme TEXT NOT NULL DEFAULT 'system', notifications INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS sessions (token_hash TEXT PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, expires_at INTEGER NOT NULL, created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS otp_codes (phone TEXT PRIMARY KEY, code_hash TEXT NOT NULL, expires_at INTEGER NOT NULL, attempts INTEGER NOT NULL DEFAULT 0, last_sent_at INTEGER NOT NULL, used INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS password_resets (phone TEXT PRIMARY KEY, code_hash TEXT NOT NULL, expires_at INTEGER NOT NULL, attempts INTEGER NOT NULL DEFAULT 0, last_sent_at INTEGER NOT NULL, used INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS study_sessions (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, curriculum_version_id INTEGER REFERENCES curriculum_versions(id), subject_id INTEGER REFERENCES subjects(id), book_id INTEGER REFERENCES books(id), chapter_id INTEGER REFERENCES chapters(id), lesson_id INTEGER REFERENCES lessons(id), topic_id INTEGER REFERENCES topics(id), title TEXT NOT NULL, planned_start INTEGER, planned_end INTEGER, planned_duration INTEGER NOT NULL DEFAULT 0, actual_start INTEGER, pause_started INTEGER, ended_at INTEGER, active_duration INTEGER NOT NULL DEFAULT 0, paused_duration INTEGER NOT NULL DEFAULT 0, mode TEXT NOT NULL DEFAULT 'stopwatch', timer_duration INTEGER, priority TEXT NOT NULL DEFAULT 'medium', notes TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'planned', timezone TEXT NOT NULL, sync_key TEXT UNIQUE, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS study_session_events (id INTEGER PRIMARY KEY AUTOINCREMENT, session_id INTEGER NOT NULL REFERENCES study_sessions(id) ON DELETE CASCADE, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, type TEXT NOT NULL, at INTEGER NOT NULL, UNIQUE(session_id,type,at));
CREATE TABLE IF NOT EXISTS study_reports (id INTEGER PRIMARY KEY AUTOINCREMENT, session_id INTEGER NOT NULL UNIQUE REFERENCES study_sessions(id) ON DELETE CASCADE, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, questions INTEGER NOT NULL DEFAULT 0, correct INTEGER NOT NULL DEFAULT 0, wrong INTEGER NOT NULL DEFAULT 0, unanswered INTEGER NOT NULL DEFAULT 0, difficulty INTEGER, understanding INTEGER, notes TEXT NOT NULL DEFAULT '', created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS tasks (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, title TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', subject_id INTEGER REFERENCES subjects(id), topic_id INTEGER REFERENCES topics(id), priority TEXT NOT NULL DEFAULT 'medium', deadline INTEGER, reminder_at INTEGER, status TEXT NOT NULL DEFAULT 'open', created_at INTEGER NOT NULL, completed_at INTEGER);
CREATE TABLE IF NOT EXISTS exams (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, title TEXT NOT NULL, exam_at INTEGER NOT NULL, subject_ids TEXT NOT NULL DEFAULT '[]', topic_ids TEXT NOT NULL DEFAULT '[]', notes TEXT NOT NULL DEFAULT '', created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS achievements (id INTEGER PRIMARY KEY AUTOINCREMENT, code TEXT NOT NULL UNIQUE, title TEXT NOT NULL, description TEXT NOT NULL, rule_type TEXT NOT NULL, threshold INTEGER NOT NULL, active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS user_achievements (user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, achievement_id INTEGER NOT NULL REFERENCES achievements(id), unlocked_at INTEGER NOT NULL, PRIMARY KEY(user_id,achievement_id));
CREATE TABLE IF NOT EXISTS study_rooms (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', active INTEGER NOT NULL DEFAULT 1, created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS study_room_memberships (room_id INTEGER NOT NULL REFERENCES study_rooms(id) ON DELETE CASCADE, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, joined_at INTEGER NOT NULL, left_at INTEGER, studying_since INTEGER, studied_duration INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(room_id,user_id));
CREATE TABLE IF NOT EXISTS notifications (id INTEGER PRIMARY KEY AUTOINCREMENT, type TEXT NOT NULL, title TEXT NOT NULL, body TEXT NOT NULL, created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS user_notifications (user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, notification_id INTEGER NOT NULL REFERENCES notifications(id) ON DELETE CASCADE, read_at INTEGER, delivered_at INTEGER, UNIQUE(user_id,notification_id));
CREATE TABLE IF NOT EXISTS audit_logs (id INTEGER PRIMARY KEY AUTOINCREMENT, admin_user TEXT NOT NULL, action TEXT NOT NULL, entity TEXT NOT NULL, entity_id TEXT, details TEXT NOT NULL DEFAULT '{}', created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS admin_tokens (token_hash TEXT PRIMARY KEY, expires_at INTEGER NOT NULL, created_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS idx_study_user_status ON study_sessions(user_id,status);
CREATE INDEX IF NOT EXISTS idx_study_user_end ON study_sessions(user_id,ended_at);
CREATE INDEX IF NOT EXISTS idx_tasks_user_deadline ON tasks(user_id,deadline);
CREATE INDEX IF NOT EXISTS idx_exams_user_date ON exams(user_id,exam_at);
`);

const year = new Date().getFullYear() >= 2026 ? '۱۴۰۵–۱۴۰۶' : '۱۴۰۴–۱۴۰۵';
db.prepare('INSERT OR IGNORE INTO academic_years(id,title,active) VALUES(1,?,1)').run(year);
const achievementSeeds = [
  ['first_session','اولین قدم','اولین جلسهٔ مطالعه را کامل کن','sessions',1],
  ['focused_hour','یک ساعت تمرکز','مجموع مطالعه را به یک ساعت برسان','seconds',3600],
  ['ten_tasks','منظم و پیگیر','ده تکلیف را کامل کن','tasks',10]
];
for (const a of achievementSeeds) db.prepare('INSERT OR IGNORE INTO achievements(code,title,description,rule_type,threshold) VALUES(?,?,?,?,?)').run(...a);

function json(res:http.ServerResponse,status:number,data:unknown){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8'});res.end(JSON.stringify(data));}
function cookie(req:http.IncomingMessage,name:string){const raw=req.headers.cookie||'';return raw.split(';').map(x=>x.trim()).find(x=>x.startsWith(name+'='))?.slice(name.length+1)||'';}
async function body(req:http.IncomingMessage){let raw='';for await(const chunk of req){raw+=chunk;if(raw.length>1_000_000)throw new Error('payload_too_large');}return raw?JSON.parse(raw):{};}
function digits(value:string){return String(value||'').replace(/[۰-۹]/g,d=>String('۰۱۲۳۴۵۶۷۸۹'.indexOf(d))).replace(/[٠-٩]/g,d=>String('٠١٢٣٤٥٦٧٨٩'.indexOf(d)));}
function normalizePhone(value:string){const v=digits(value).replace(/\D/g,'');return v.startsWith('98')?'0'+v.slice(2):v;}
function hashToken(value:string){return crypto.createHash('sha256').update(value).digest('hex');}
function otpHash(code:string,phone:string){return crypto.createHmac('sha256',OTP_SECRET).update(code+phone).digest('hex');}
async function passwordHash(password:string){const salt=crypto.randomBytes(16).toString('hex');const key=await scrypt(password,salt,64) as Buffer;return salt+':'+key.toString('hex');}
async function passwordValid(password:string,stored:string){const [salt,hex]=stored.split(':');if(!salt||!hex)return false;const key=await scrypt(password,salt,64) as Buffer;const expected=Buffer.from(hex,'hex');return expected.length===key.length&&crypto.timingSafeEqual(expected,key);}
function currentUser(req:http.IncomingMessage){const token=cookie(req,COOKIE);if(!token)return null;return db.prepare(`SELECT u.id,u.first_name,u.last_name,u.phone,u.verified,p.grade,p.field,p.timezone,p.daily_goal,p.curriculum_version_id,a.title academic_year FROM sessions s JOIN users u ON u.id=s.user_id JOIN user_profiles p ON p.user_id=u.id JOIN academic_years a ON a.id=p.academic_year_id WHERE s.token_hash=? AND s.expires_at>? AND u.deleted_at IS NULL`).get(hashToken(token),Date.now()) as any||null;}
function requireUser(req:http.IncomingMessage,res:http.ServerResponse){const u=currentUser(req);if(!u)json(res,401,{error:'نشست شما معتبر نیست؛ دوباره وارد شوید'});return u;}
function validPhone(phone:string){return /^09\d{9}$/.test(phone);}
function validField(field:string){return ['math','science','humanities'].includes(field);}
function validGrade(grade:number){return [10,11,12].includes(grade);}
function safeText(v:unknown,max=500){return String(v??'').trim().slice(0,max);}
function makeSession(res:http.ServerResponse,userId:number){const token=crypto.randomBytes(32).toString('base64url');const now=Date.now();db.prepare('INSERT INTO sessions(token_hash,user_id,expires_at,created_at) VALUES(?,?,?,?)').run(hashToken(token),userId,now+SESSION_MS,now);res.setHeader('Set-Cookie',`${COOKIE}=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=${SESSION_MS/1000}`);}
async function sendOtp(phone:string,code:string){const url=process.env.PLATFORM_SERVICES_URL,token=process.env.PLATFORM_SERVICE_TOKEN;if(!url||!token)throw new Error('sms_unavailable');const r=await fetch(url+'/sms/otp',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({phone,code})});if(!r.ok){const e:any=new Error('sms_'+r.status);e.status=r.status;throw e;}}
async function issueCode(table:'otp_codes'|'password_resets',phone:string){const existing=db.prepare(`SELECT last_sent_at FROM ${table} WHERE phone=?`).get(phone) as any;const now=Date.now();if(existing&&now-existing.last_sent_at<60000){const e:any=new Error('cooldown');e.status=429;throw e;}const code=String(crypto.randomInt(10000,100000));await sendOtp(phone,code);db.prepare(`INSERT INTO ${table}(phone,code_hash,expires_at,attempts,last_sent_at,used) VALUES(?,?,?,?,?,0) ON CONFLICT(phone) DO UPDATE SET code_hash=excluded.code_hash,expires_at=excluded.expires_at,attempts=0,last_sent_at=excluded.last_sent_at,used=0`).run(phone,otpHash(code,phone),now+120000,0,now);}
function verifyCode(table:'otp_codes'|'password_resets',phone:string,input:string){const row=db.prepare(`SELECT * FROM ${table} WHERE phone=?`).get(phone) as any;if(!row||row.used||row.expires_at<Date.now()||row.attempts>=5)return false;const ok=crypto.timingSafeEqual(Buffer.from(row.code_hash),Buffer.from(otpHash(input,phone)));if(!ok){db.prepare(`UPDATE ${table} SET attempts=attempts+1 WHERE phone=?`).run(phone);return false;}db.prepare(`UPDATE ${table} SET used=1 WHERE phone=?`).run(phone);return true;}
function curriculumFor(grade:number,field:string,yearId=1){return db.prepare("SELECT id FROM curriculum_versions WHERE academic_year_id=? AND grade=? AND field=? AND status='published' ORDER BY updated_at DESC LIMIT 1").get(yearId,grade,field) as any;}
function assertCurriculumOwner(user:any,id:any,table:string){if(!id)return true;const columns:{[k:string]:string}={subjects:'s.id',books:'b.id',chapters:'c.id',lessons:'l.id',topics:'t.id'};const joins:{[k:string]:string}={subjects:'subjects s',books:'books b JOIN subjects s ON s.id=b.subject_id',chapters:'chapters c JOIN books b ON b.id=c.book_id JOIN subjects s ON s.id=b.subject_id',lessons:'lessons l JOIN chapters c ON c.id=l.chapter_id JOIN books b ON b.id=c.book_id JOIN subjects s ON s.id=b.subject_id',topics:'topics t JOIN lessons l ON l.id=t.lesson_id JOIN chapters c ON c.id=l.chapter_id JOIN books b ON b.id=c.book_id JOIN subjects s ON s.id=b.subject_id'};return !!db.prepare(`SELECT 1 FROM ${joins[table]} WHERE ${columns[table]}=? AND s.curriculum_version_id=?`).get(id,user.curriculum_version_id);}
function unlock(userId:number){const stats=db.prepare("SELECT COUNT(*) sessions,COALESCE(SUM(active_duration),0) seconds FROM study_sessions WHERE user_id=? AND status='completed'").get(userId) as any;const tasks=db.prepare("SELECT COUNT(*) tasks FROM tasks WHERE user_id=? AND status='completed'").get(userId) as any;const all=db.prepare('SELECT * FROM achievements WHERE active=1').all() as any[];for(const a of all){const val=a.rule_type==='sessions'?stats.sessions:a.rule_type==='seconds'?stats.seconds:tasks.tasks;if(val>=a.threshold)db.prepare('INSERT OR IGNORE INTO user_achievements(user_id,achievement_id,unlocked_at) VALUES(?,?,?)').run(userId,a.id,Date.now());}}
function activeSeconds(s:any,now=Date.now()){if(!s.actual_start)return s.active_duration||0;if(s.status==='active')return s.active_duration+Math.max(0,now-s.actual_start)/1000;if(s.status==='paused')return s.active_duration;return s.active_duration||0;}
function stats(userId:number){const now=new Date();const today=new Date(now.getFullYear(),now.getMonth(),now.getDate()).getTime();const week=today-6*86400000;const month=new Date(now.getFullYear(),now.getMonth(),1).getTime();const rows=db.prepare("SELECT ended_at,active_duration FROM study_sessions WHERE user_id=? AND status='completed'").all(userId) as any[];const total=(from:number)=>Math.round(rows.filter(r=>r.ended_at>=from).reduce((a,r)=>a+r.active_duration,0));const task=db.prepare("SELECT COUNT(*) total,SUM(CASE WHEN status='completed' THEN 1 ELSE 0 END) done FROM tasks WHERE user_id=?").get(userId) as any;const q=db.prepare('SELECT COALESCE(SUM(questions),0) q,COALESCE(SUM(correct),0) c FROM study_reports WHERE user_id=?').get(userId) as any;const days=new Set(rows.map(r=>new Date(r.ended_at).toISOString().slice(0,10)));let streak=0;for(let i=0;i<365;i++){const d=new Date(today-i*86400000).toISOString().slice(0,10);if(days.has(d))streak++;else if(i>0||days.size)break;}return {today:total(today),week:total(week),month:total(month),all:total(0),sessions:rows.length,tasksTotal:task.total||0,tasksDone:task.done||0,questions:q.q,accuracy:q.q?Math.round(q.c/q.q*100):0,streak};}
function adminOk(req:http.IncomingMessage){const token=String(req.headers['x-admin-token']||'');return !!token&&!!db.prepare('SELECT 1 FROM admin_tokens WHERE token_hash=? AND expires_at>?').get(hashToken(token),Date.now());}
function audit(action:string,entity:string,id:unknown,details:unknown={}){db.prepare('INSERT INTO audit_logs(admin_user,action,entity,entity_id,details,created_at) VALUES(?,?,?,?,?,?)').run(ADMIN_USER,action,entity,String(id??''),JSON.stringify(details),Date.now());}

const server=http.createServer(async(req,res)=>{
 try{
  const url=new URL(req.url||'/',`http://${req.headers.host||'localhost'}`);const path=url.pathname;const method=req.method||'GET';
  if(path==='/api/health')return json(res,200,{ok:true});
  if(path==='/api/auth/register'&&method==='POST'){const b=await body(req),phone=normalizePhone(b.phone),grade=Number(b.grade),field=safeText(b.field),first=safeText(b.firstName,60),last=safeText(b.lastName,60),password=String(b.password||''),timezone=safeText(b.timezone,80)||'Asia/Tehran';if(!first||!last||!validPhone(phone)||!validGrade(grade)||!validField(field)||password.length<8||password!==b.passwordConfirm)return json(res,400,{error:'اطلاعات ثبت‌نام کامل یا معتبر نیست'});if(db.prepare('SELECT 1 FROM users WHERE phone=? AND deleted_at IS NULL').get(phone))return json(res,409,{error:'این شماره قبلاً ثبت شده است'});const hash=await passwordHash(password);const now=Date.now();db.exec('BEGIN');try{const r=db.prepare('INSERT INTO users(first_name,last_name,phone,password_hash,created_at) VALUES(?,?,?,?,?)').run(first,last,phone,hash,now);const uid=Number(r.lastInsertRowid);const cv=curriculumFor(grade,field);db.prepare('INSERT INTO user_profiles(user_id,grade,field,academic_year_id,timezone,curriculum_version_id) VALUES(?,?,?,?,?,?)').run(uid,grade,field,1,timezone,cv?.id||null);db.prepare('INSERT INTO user_settings(user_id) VALUES(?)').run(uid);db.exec('COMMIT');await issueCode('otp_codes',phone);return json(res,201,{ok:true,needsVerification:true});}catch(e){db.exec('ROLLBACK');throw e;}}
  if(path==='/api/auth/verify'&&method==='POST'){const b=await body(req),phone=normalizePhone(b.phone),code=digits(String(b.code||'')).trim();if(!verifyCode('otp_codes',phone,code))return json(res,400,{error:'کد نامعتبر یا منقضی است'});const u=db.prepare('SELECT id FROM users WHERE phone=? AND deleted_at IS NULL').get(phone) as any;if(!u)return json(res,404,{error:'حساب پیدا نشد'});db.prepare('UPDATE users SET verified=1 WHERE id=?').run(u.id);makeSession(res,u.id);return json(res,200,{ok:true});}
  if(path==='/api/auth/login'&&method==='POST'){const b=await body(req),phone=normalizePhone(b.phone);const u=db.prepare('SELECT * FROM users WHERE phone=? AND deleted_at IS NULL').get(phone) as any;if(!u||!await passwordValid(String(b.password||''),u.password_hash))return json(res,401,{error:'شماره یا رمز عبور نادرست است'});if(!u.verified)return json(res,403,{error:'حساب هنوز تأیید نشده است',needsVerification:true});makeSession(res,u.id);return json(res,200,{ok:true});}
  if(path==='/api/auth/logout'&&method==='POST'){const token=cookie(req,COOKIE);if(token)db.prepare('DELETE FROM sessions WHERE token_hash=?').run(hashToken(token));res.setHeader('Set-Cookie',`${COOKIE}=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0`);return json(res,200,{ok:true});}
  if(path==='/api/auth/forgot'&&method==='POST'){const phone=normalizePhone((await body(req)).phone);if(!validPhone(phone))return json(res,400,{error:'شماره موبایل معتبر نیست'});if(db.prepare('SELECT 1 FROM users WHERE phone=? AND deleted_at IS NULL').get(phone))await issueCode('password_resets',phone);return json(res,200,{ok:true});}
  if(path==='/api/auth/reset'&&method==='POST'){const b=await body(req),phone=normalizePhone(b.phone),code=digits(String(b.code||'')),password=String(b.password||'');if(password.length<8)return json(res,400,{error:'رمز باید دست‌کم ۸ نویسه باشد'});if(!verifyCode('password_resets',phone,code))return json(res,400,{error:'کد نامعتبر یا منقضی است'});db.prepare('UPDATE users SET password_hash=? WHERE phone=?').run(await passwordHash(password),phone);db.prepare('DELETE FROM sessions WHERE user_id=(SELECT id FROM users WHERE phone=?)').run(phone);return json(res,200,{ok:true});}
  if(path==='/api/me'&&method==='GET'){const u=requireUser(req,res);if(!u)return;return json(res,200,{user:u,stats:stats(u.id)});}
  if(path==='/api/me'&&method==='PATCH'){const u=requireUser(req,res);if(!u)return;const b=await body(req),first=safeText(b.firstName,60),last=safeText(b.lastName,60),goal=Number(b.dailyGoal);if(!first||!last||!Number.isFinite(goal)||goal<900||goal>43200)return json(res,400,{error:'اطلاعات پروفایل معتبر نیست'});db.prepare('UPDATE users SET first_name=?,last_name=? WHERE id=?').run(first,last,u.id);db.prepare('UPDATE user_profiles SET daily_goal=? WHERE user_id=?').run(goal,u.id);return json(res,200,{ok:true});}
  if(path==='/api/me'&&method==='DELETE'){const u=requireUser(req,res);if(!u)return;db.prepare('UPDATE users SET deleted_at=? WHERE id=?').run(Date.now(),u.id);db.prepare('DELETE FROM sessions WHERE user_id=?').run(u.id);res.setHeader('Set-Cookie',`${COOKIE}=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0`);return json(res,200,{ok:true});}
  if(path==='/api/curriculum'&&method==='GET'){const u=requireUser(req,res);if(!u)return;if(!u.curriculum_version_id)return json(res,200,{version:null,subjects:[]});const subjects=db.prepare('SELECT id,name FROM subjects WHERE curriculum_version_id=? ORDER BY sort_order,id').all(u.curriculum_version_id) as any[];for(const s of subjects){s.books=db.prepare('SELECT id,name FROM books WHERE subject_id=? ORDER BY sort_order,id').all(s.id);}return json(res,200,{version:u.curriculum_version_id,subjects});}
  if(path==='/api/dashboard'&&method==='GET'){const u=requireUser(req,res);if(!u)return;const now=Date.now(),today=new Date();today.setHours(0,0,0,0);const tasks=db.prepare('SELECT * FROM tasks WHERE user_id=? AND status!=? AND (deadline IS NULL OR deadline<?) ORDER BY deadline LIMIT 6').all(u.id,'completed',today.getTime()+86400000);const exams=db.prepare('SELECT * FROM exams WHERE user_id=? AND exam_at>=? ORDER BY exam_at LIMIT 5').all(u.id,now);const plan=db.prepare("SELECT * FROM study_sessions WHERE user_id=? AND status='planned' AND planned_start>=? AND planned_start<? ORDER BY planned_start").all(u.id,today.getTime(),today.getTime()+86400000);const active=db.prepare("SELECT * FROM study_sessions WHERE user_id=? AND status IN ('active','paused') LIMIT 1").get(u.id) as any;const achievements=db.prepare('SELECT a.*,ua.unlocked_at FROM user_achievements ua JOIN achievements a ON a.id=ua.achievement_id WHERE ua.user_id=? ORDER BY ua.unlocked_at DESC').all(u.id);return json(res,200,{stats:stats(u.id),tasks,exams,plan,active:active?{...active,liveSeconds:Math.round(activeSeconds(active))}:null,achievements});}
  if(path==='/api/tasks'&&method==='GET'){const u=requireUser(req,res);if(!u)return;return json(res,200,{items:db.prepare('SELECT * FROM tasks WHERE user_id=? ORDER BY status,deadline,created_at DESC LIMIT 200').all(u.id)});}
  if(path==='/api/tasks'&&method==='POST'){const u=requireUser(req,res);if(!u)return;const b=await body(req),title=safeText(b.title,160),deadline=b.deadline?Number(b.deadline):null;if(!title||deadline&&deadline<Date.now()-86400000)return json(res,400,{error:'عنوان یا زمان تکلیف معتبر نیست'});const r=db.prepare('INSERT INTO tasks(user_id,title,description,subject_id,priority,deadline,reminder_at,created_at) VALUES(?,?,?,?,?,?,?,?)').run(u.id,title,safeText(b.description,1000),b.subjectId||null,safeText(b.priority)||'medium',deadline,b.reminderAt||null,Date.now());return json(res,201,{id:Number(r.lastInsertRowid)});}
  if(path.match(/^\/api\/tasks\/\d+$/)&&['PATCH','DELETE'].includes(method)){const u=requireUser(req,res);if(!u)return;const id=Number(path.split('/').pop()),task=db.prepare('SELECT * FROM tasks WHERE id=? AND user_id=?').get(id,u.id) as any;if(!task)return json(res,404,{error:'تکلیف پیدا نشد'});if(method==='DELETE'){db.prepare('DELETE FROM tasks WHERE id=? AND user_id=?').run(id,u.id);return json(res,200,{ok:true});}const b=await body(req),status=b.status==='completed'?'completed':b.status==='open'?'open':task.status;db.prepare('UPDATE tasks SET title=?,description=?,priority=?,deadline=?,status=?,completed_at=? WHERE id=? AND user_id=?').run(safeText(b.title??task.title,160),safeText(b.description??task.description,1000),safeText(b.priority??task.priority),b.deadline??task.deadline,status,status==='completed'?Date.now():null,id,u.id);unlock(u.id);return json(res,200,{ok:true});}
  if(path==='/api/exams'&&method==='GET'){const u=requireUser(req,res);if(!u)return;return json(res,200,{items:db.prepare('SELECT * FROM exams WHERE user_id=? ORDER BY exam_at LIMIT 100').all(u.id)});}
  if(path==='/api/exams'&&method==='POST'){const u=requireUser(req,res);if(!u)return;const b=await body(req),title=safeText(b.title,160),at=Number(b.examAt);if(!title||!Number.isFinite(at)||at<=Date.now())return json(res,400,{error:'عنوان و زمان آینده برای آزمون لازم است'});const r=db.prepare('INSERT INTO exams(user_id,title,exam_at,subject_ids,topic_ids,notes,created_at) VALUES(?,?,?,?,?,?,?)').run(u.id,title,at,JSON.stringify(b.subjectIds||[]),JSON.stringify(b.topicIds||[]),safeText(b.notes,1000),Date.now());return json(res,201,{id:Number(r.lastInsertRowid)});}
  if(path.match(/^\/api\/exams\/\d+$/)&&method==='DELETE'){const u=requireUser(req,res);if(!u)return;db.prepare('DELETE FROM exams WHERE id=? AND user_id=?').run(Number(path.split('/').pop()),u.id);return json(res,200,{ok:true});}
  if(path==='/api/planner'&&method==='GET'){const u=requireUser(req,res);if(!u)return;const from=Number(url.searchParams.get('from')||0),to=Number(url.searchParams.get('to')||Date.now()+30*86400000);return json(res,200,{items:db.prepare('SELECT s.*,sub.name subject_name FROM study_sessions s LEFT JOIN subjects sub ON sub.id=s.subject_id WHERE s.user_id=? AND COALESCE(s.planned_start,s.created_at)>=? AND COALESCE(s.planned_start,s.created_at)<? ORDER BY COALESCE(s.planned_start,s.created_at)').all(u.id,from,to)});}
  if(path==='/api/planner'&&method==='POST'){const u=requireUser(req,res);if(!u)return;const b=await body(req),start=Number(b.start),end=Number(b.end),title=safeText(b.title,160);if(!title||!Number.isFinite(start)||!Number.isFinite(end)||end<=start||end-start>12*3600000)return json(res,400,{error:'زمان‌بندی معتبر نیست'});const overlap=db.prepare("SELECT 1 FROM study_sessions WHERE user_id=? AND status NOT IN ('cancelled','completed') AND planned_start<? AND planned_end>?").get(u.id,end,start);if(overlap)return json(res,409,{error:'این بازه با برنامهٔ دیگری تداخل دارد'});if(b.subjectId&&!assertCurriculumOwner(u,b.subjectId,'subjects'))return json(res,400,{error:'درس با برنامهٔ تحصیلی شما سازگار نیست'});const now=Date.now(),r=db.prepare('INSERT INTO study_sessions(user_id,curriculum_version_id,subject_id,title,planned_start,planned_end,planned_duration,priority,notes,status,timezone,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').run(u.id,u.curriculum_version_id,b.subjectId||null,title,start,end,Math.round((end-start)/1000),safeText(b.priority)||'medium',safeText(b.notes,1000),'planned',u.timezone,now,now);return json(res,201,{id:Number(r.lastInsertRowid)});}
  if(path.match(/^\/api\/planner\/\d+$/)&&['PATCH','DELETE'].includes(method)){const u=requireUser(req,res);if(!u)return;const id=Number(path.split('/').pop()),s=db.prepare('SELECT * FROM study_sessions WHERE id=? AND user_id=?').get(id,u.id) as any;if(!s)return json(res,404,{error:'جلسه پیدا نشد'});if(method==='DELETE'){if(['active','paused'].includes(s.status))return json(res,409,{error:'ابتدا زمان‌سنج را متوقف کنید'});db.prepare('DELETE FROM study_sessions WHERE id=? AND user_id=?').run(id,u.id);return json(res,200,{ok:true});}const b=await body(req);if(b.action==='duplicate'){const ns=(s.planned_start||Date.now())+86400000,ne=(s.planned_end||ns+s.planned_duration*1000)+86400000;const overlap=db.prepare("SELECT 1 FROM study_sessions WHERE user_id=? AND status NOT IN ('cancelled','completed') AND planned_start<? AND planned_end>?").get(u.id,ne,ns);if(overlap)return json(res,409,{error:'نسخهٔ تکراری با برنامه‌ای دیگر تداخل دارد'});db.prepare('INSERT INTO study_sessions(user_id,curriculum_version_id,subject_id,title,planned_start,planned_end,planned_duration,priority,notes,status,timezone,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').run(u.id,s.curriculum_version_id,s.subject_id,s.title,ns,ne,s.planned_duration,s.priority,s.notes,'planned',s.timezone,Date.now(),Date.now());return json(res,200,{ok:true});}if(b.action==='cancel'||b.action==='complete'){db.prepare('UPDATE study_sessions SET status=?,updated_at=? WHERE id=? AND user_id=?').run(b.action==='cancel'?'cancelled':'completed',Date.now(),id,u.id);unlock(u.id);return json(res,200,{ok:true});}return json(res,400,{error:'عملیات معتبر نیست'});}
  if(path==='/api/timer/start'&&method==='POST'){const u=requireUser(req,res);if(!u)return;const b=await body(req),now=Date.now();if(db.prepare("SELECT 1 FROM study_sessions WHERE user_id=? AND status IN ('active','paused')").get(u.id))return json(res,409,{error:'یک زمان‌سنج دیگر فعال است'});const duration=b.duration?Number(b.duration):null;if(duration!==null&&(!Number.isFinite(duration)||duration<60||duration>43200))return json(res,400,{error:'مدت زمان‌سنج معتبر نیست'});const r=db.prepare('INSERT INTO study_sessions(user_id,curriculum_version_id,subject_id,title,actual_start,mode,timer_duration,status,timezone,sync_key,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run(u.id,u.curriculum_version_id,b.subjectId||null,safeText(b.title,160)||'مطالعه آزاد',now,safeText(b.mode)||'stopwatch',duration,'active',u.timezone,safeText(b.syncKey,100)||crypto.randomUUID(),now,now);db.prepare('INSERT INTO study_session_events(session_id,user_id,type,at) VALUES(?,?,?,?)').run(Number(r.lastInsertRowid),u.id,'start',now);return json(res,201,{id:Number(r.lastInsertRowid),startedAt:now});}
  if(path==='/api/timer/active'&&method==='GET'){const u=requireUser(req,res);if(!u)return;const s=db.prepare("SELECT * FROM study_sessions WHERE user_id=? AND status IN ('active','paused') LIMIT 1").get(u.id) as any;return json(res,200,{session:s?{...s,liveSeconds:Math.round(activeSeconds(s))}:null,serverNow:Date.now()});}
  if(path==='/api/timer/action'&&method==='POST'){const u=requireUser(req,res);if(!u)return;const b=await body(req),action=safeText(b.action),s=db.prepare("SELECT * FROM study_sessions WHERE user_id=? AND status IN ('active','paused') LIMIT 1").get(u.id) as any;if(!s)return json(res,404,{error:'زمان‌سنج فعالی وجود ندارد'});const now=Date.now();if(action==='pause'&&s.status==='active'){const active=s.active_duration+Math.max(0,now-s.actual_start)/1000;db.prepare("UPDATE study_sessions SET status='paused',active_duration=?,pause_started=?,actual_start=NULL,updated_at=? WHERE id=? AND user_id=?").run(Math.round(active),now,now,s.id,u.id);}else if(action==='resume'&&s.status==='paused'){const paused=s.paused_duration+Math.max(0,now-s.pause_started)/1000;db.prepare("UPDATE study_sessions SET status='active',paused_duration=?,actual_start=?,pause_started=NULL,updated_at=? WHERE id=? AND user_id=?").run(Math.round(paused),now,now,s.id,u.id);}else if(['finish','stop','cancel'].includes(action)){let active=s.active_duration;if(s.status==='active')active+=Math.max(0,now-s.actual_start)/1000;const status=action==='cancel'?'cancelled':'completed';db.prepare('UPDATE study_sessions SET status=?,active_duration=?,ended_at=?,actual_start=NULL,pause_started=NULL,updated_at=? WHERE id=? AND user_id=?').run(status,Math.round(active),now,now,s.id,u.id);if(status==='completed')unlock(u.id);}else return json(res,400,{error:'این عملیات در وضعیت فعلی ممکن نیست'});db.prepare('INSERT OR IGNORE INTO study_session_events(session_id,user_id,type,at) VALUES(?,?,?,?)').run(s.id,u.id,action,now);return json(res,200,{ok:true});}
  if(path==='/api/reports'&&method==='POST'){const u=requireUser(req,res);if(!u)return;const b=await body(req),sid=Number(b.sessionId),s=db.prepare("SELECT * FROM study_sessions WHERE id=? AND user_id=? AND status='completed'").get(sid,u.id) as any;if(!s)return json(res,404,{error:'جلسهٔ کامل‌شده پیدا نشد'});const q=Number(b.questions||0),c=Number(b.correct||0),w=Number(b.wrong||0),un=Number(b.unanswered||0);if([q,c,w,un].some(x=>!Number.isInteger(x)||x<0)||c+w+un!==q)return json(res,400,{error:'جمع پاسخ‌ها باید با تعداد سؤال‌ها برابر باشد'});db.prepare('INSERT INTO study_reports(session_id,user_id,questions,correct,wrong,unanswered,difficulty,understanding,notes,created_at) VALUES(?,?,?,?,?,?,?,?,?,?) ON CONFLICT(session_id) DO UPDATE SET questions=excluded.questions,correct=excluded.correct,wrong=excluded.wrong,unanswered=excluded.unanswered,difficulty=excluded.difficulty,understanding=excluded.understanding,notes=excluded.notes').run(sid,u.id,q,c,w,un,b.difficulty||null,b.understanding||null,safeText(b.notes,1000),Date.now());return json(res,200,{ok:true});}
  if(path==='/api/statistics'&&method==='GET'){const u=requireUser(req,res);if(!u)return;const bySubject=db.prepare("SELECT COALESCE(sub.name,'مطالعه آزاد') name,SUM(s.active_duration) seconds,COUNT(*) sessions FROM study_sessions s LEFT JOIN subjects sub ON sub.id=s.subject_id WHERE s.user_id=? AND s.status='completed' GROUP BY sub.name ORDER BY seconds DESC").all(u.id);return json(res,200,{summary:stats(u.id),bySubject});}
  if(path==='/api/search'&&method==='GET'){const u=requireUser(req,res);if(!u)return;const q=safeText(url.searchParams.get('q'),100).replace(/ي/g,'ی').replace(/ك/g,'ک').replace(/[‌\s]+/g,' ').trim();if(q.length<2)return json(res,200,{items:[]});const like='%'+q+'%';const items:any[]=[];for(const r of db.prepare('SELECT id,title name,\'task\' type FROM tasks WHERE user_id=? AND REPLACE(REPLACE(title,\'ي\',\'ی\'),\'ك\',\'ک\') LIKE ? LIMIT 20').all(u.id,like) as any[])items.push(r);for(const r of db.prepare('SELECT id,title name,\'exam\' type FROM exams WHERE user_id=? AND title LIKE ? LIMIT 20').all(u.id,like) as any[])items.push(r);if(u.curriculum_version_id)for(const r of db.prepare("SELECT id,name,'subject' type FROM subjects WHERE curriculum_version_id=? AND name LIKE ? LIMIT 20").all(u.curriculum_version_id,like) as any[])items.push(r);return json(res,200,{items});}
  if(path==='/api/rooms'&&method==='GET'){const u=requireUser(req,res);if(!u)return;const rooms=db.prepare(`SELECT r.*,COUNT(CASE WHEN m.left_at IS NULL THEN 1 END) participants,COALESCE(SUM(m.studied_duration + CASE WHEN m.studying_since IS NOT NULL THEN (? - m.studying_since)/1000 ELSE 0 END),0) studied_seconds FROM study_rooms r LEFT JOIN study_room_memberships m ON m.room_id=r.id WHERE r.active=1 GROUP BY r.id ORDER BY participants DESC,r.name`).all(Date.now());return json(res,200,{items:rooms});}
  if(path.match(/^\/api\/rooms\/\d+\/(join|leave|start|stop)$/)&&method==='POST'){const u=requireUser(req,res);if(!u)return;const parts=path.split('/'),id=Number(parts[3]),action=parts[4],now=Date.now();if(!db.prepare('SELECT 1 FROM study_rooms WHERE id=? AND active=1').get(id))return json(res,404,{error:'اتاق پیدا نشد'});if(action==='join')db.prepare('INSERT INTO study_room_memberships(room_id,user_id,joined_at,left_at) VALUES(?,?,?,NULL) ON CONFLICT(room_id,user_id) DO UPDATE SET left_at=NULL,joined_at=excluded.joined_at').run(id,u.id,now);if(action==='leave')db.prepare('UPDATE study_room_memberships SET studied_duration=studied_duration+CASE WHEN studying_since IS NOT NULL THEN (? - studying_since)/1000 ELSE 0 END,studying_since=NULL,left_at=? WHERE room_id=? AND user_id=?').run(now,now,id,u.id);if(action==='start')db.prepare('UPDATE study_room_memberships SET studying_since=? WHERE room_id=? AND user_id=? AND left_at IS NULL AND studying_since IS NULL').run(now,id,u.id);if(action==='stop')db.prepare('UPDATE study_room_memberships SET studied_duration=studied_duration+CASE WHEN studying_since IS NOT NULL THEN (? - studying_since)/1000 ELSE 0 END,studying_since=NULL WHERE room_id=? AND user_id=?').run(now,id,u.id);return json(res,200,{ok:true});}
  if(path==='/api/admin/login'&&method==='POST'){const b=await body(req);if(safeText(b.username)!==ADMIN_USER||String(b.password)!==ADMIN_PASSWORD)return json(res,401,{error:'اطلاعات ورود نادرست است'});const token=crypto.randomBytes(32).toString('base64url');db.prepare('INSERT INTO admin_tokens(token_hash,expires_at,created_at) VALUES(?,?,?)').run(hashToken(token),Date.now()+12*3600000,Date.now());audit('login','admin','owner');return json(res,200,{token});}
  if(path.startsWith('/api/admin/')){if(!adminOk(req))return json(res,401,{error:'دسترسی مدیریت معتبر نیست'});
   if(path==='/api/admin/overview'&&method==='GET')return json(res,200,{users:(db.prepare('SELECT COUNT(*) c FROM users WHERE deleted_at IS NULL').get() as any).c,versions:db.prepare('SELECT cv.*,a.title academic_year FROM curriculum_versions cv JOIN academic_years a ON a.id=cv.academic_year_id ORDER BY cv.updated_at DESC').all(),rooms:db.prepare('SELECT * FROM study_rooms ORDER BY created_at DESC').all(),audits:db.prepare('SELECT * FROM audit_logs ORDER BY created_at DESC LIMIT 50').all()});
   if(path==='/api/admin/curriculum/import'&&method==='POST'){const b=await body(req),grade=Number(b.grade),field=safeText(b.field),title=safeText(b.title,160),tree=b.tree;if(!validGrade(grade)||!validField(field)||!title||!Array.isArray(tree))return json(res,400,{error:'ساختار محتوای درسی معتبر نیست'});const now=Date.now();db.exec('BEGIN');try{const r=db.prepare("INSERT INTO curriculum_versions(academic_year_id,grade,field,status,title,created_at,updated_at) VALUES(1,?,?,'draft',?,?,?)").run(grade,field,title,now,now);const version=Number(r.lastInsertRowid);for(let si=0;si<tree.length;si++){const s=tree[si];if(!safeText(s.name))throw new Error('invalid_subject');const sr=db.prepare('INSERT INTO subjects(curriculum_version_id,name,sort_order) VALUES(?,?,?)').run(version,safeText(s.name,160),si);for(let bi=0;bi<(s.books||[]).length;bi++){const book=s.books[bi],br=db.prepare('INSERT INTO books(subject_id,name,sort_order) VALUES(?,?,?)').run(Number(sr.lastInsertRowid),safeText(book.name,160),bi);for(let ci=0;ci<(book.chapters||[]).length;ci++){const ch=book.chapters[ci],cr=db.prepare('INSERT INTO chapters(book_id,name,sort_order) VALUES(?,?,?)').run(Number(br.lastInsertRowid),safeText(ch.name,160),ci);for(let li=0;li<(ch.lessons||[]).length;li++){const lesson=ch.lessons[li],lr=db.prepare('INSERT INTO lessons(chapter_id,name,sort_order) VALUES(?,?,?)').run(Number(cr.lastInsertRowid),safeText(lesson.name,160),li);for(let ti=0;ti<(lesson.topics||[]).length;ti++)db.prepare('INSERT INTO topics(lesson_id,name,sort_order) VALUES(?,?,?)').run(Number(lr.lastInsertRowid),safeText(lesson.topics[ti],160),ti);}}}}db.exec('COMMIT');audit('import','curriculum',version,{grade,field,title});return json(res,201,{id:version});}catch(e){db.exec('ROLLBACK');throw e;}}
   if(path.match(/^\/api\/admin\/curriculum\/\d+\/status$/)&&method==='POST'){const id=Number(path.split('/')[4]),status=safeText((await body(req)).status);if(!['review','published','archived'].includes(status))return json(res,400,{error:'وضعیت معتبر نیست'});const v=db.prepare('SELECT * FROM curriculum_versions WHERE id=?').get(id) as any;if(!v)return json(res,404,{error:'نسخه پیدا نشد'});db.exec('BEGIN');try{if(status==='published'){db.prepare("UPDATE curriculum_versions SET status='archived',updated_at=? WHERE academic_year_id=? AND grade=? AND field=? AND status='published'").run(Date.now(),v.academic_year_id,v.grade,v.field);}db.prepare('UPDATE curriculum_versions SET status=?,updated_at=? WHERE id=?').run(status,Date.now(),id);if(status==='published')db.prepare('UPDATE user_profiles SET curriculum_version_id=? WHERE grade=? AND field=? AND academic_year_id=? AND curriculum_version_id IS NULL').run(id,v.grade,v.field,v.academic_year_id);db.exec('COMMIT');audit('status_change','curriculum',id,{status});return json(res,200,{ok:true});}catch(e){db.exec('ROLLBACK');throw e;}}
   if(path==='/api/admin/rooms'&&method==='POST'){const b=await body(req),name=safeText(b.name,120);if(!name)return json(res,400,{error:'نام اتاق لازم است'});const r=db.prepare('INSERT INTO study_rooms(name,description,created_at) VALUES(?,?,?)').run(name,safeText(b.description,500),Date.now());audit('create','room',r.lastInsertRowid);return json(res,201,{id:Number(r.lastInsertRowid)});}
  }
  return json(res,404,{error:'مسیر پیدا نشد'});
 }catch(error:any){console.error('request_failed',{url:req.url,method:req.method,error});const status=error.status===429?429:error.message==='payload_too_large'?413:500;return json(res,status,{error:status===429?'تا ۶۰ ثانیهٔ دیگر دوباره تلاش کنید':'خطایی رخ داد؛ دوباره تلاش کنید'});}
});
server.listen(PORT,()=>console.log(`Darsban server listening on ${PORT}`));
